---

- name: Deploy 'zones.conf' template
  become: yes
  template:
    dest: "/etc/icinga2/zones.conf"
    src: "templates/zones.conf.j2"
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_user }}"
  notify:
    - "Restart icinga2"

- name: Deploy 'icinga2.conf' template
  become: yes
  template:
    dest: "/etc/icinga2/icinga2.conf"
    src: "templates/icinga2.conf.j2"
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_user }}"
  notify:
    - "Restart icinga2"

- name: Deploy 'constants.conf' template
  become: yes
  template:
    dest: "/etc/icinga2/constants.conf"
    src: "templates/constants.conf.j2"
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_user }}"
  notify:
    - "Restart icinga2"
